### ISSUE TITLE
Question about adaptation of FAMix on CLIP-ViT backbone & learnable text prompts

### ISSUE THREAD

**Issue by ByeongHyunPak** [astra-vision/FAMix#1]
Hi, I'm interested in your impressive work!
And I have some question.

1. Have you ever experimented with FAMix on ViT backbone?
2. If you have, how much gain is?
3. If you don't, what is the reason you don't have try?
4. Instead of chatGPT description, have you considered a learnable text prompt like [CoOp](https://arxiv.org/pdf/2109.01134.pdf)?

Thank you :)

**Comment by mfahes** [comment]
Hi, thank you for your interest in our work.
I didn't experiment FAMix on ViT backbone. The extension might not be straightforward. To my knowledge, all the discussion about the relation between low-level feature statistics and the style of the image was on CNNs. However, it could a nice extension for a future work, especially that some ViT backbone may lead to better OOD generalization. The extension could be in the scope of  [this work](https://openaccess.thecvf.com/content/CVPR2022/papers/Deng_StyTr2_Image_Style_Transfer_With_Transformers_CVPR_2022_paper.pdf)

CoOp consists of optimizing the context in a prompt for few-shot adaptation. Since we don't have access to any target image at the training time, we can't use it. It was shown in the same paper that contexts learned from the source images could be generalizable to other domains (Tab.1), but the task is different. The main point of our work is to mine proxy styles using random prompts, and diversify using style mixing between the source and mined styles. That being said, using a learned context in the prompt to mine styles might also work well when style mixing is applied, however I am not sure it improves the performance w.r.t. our prompt construction.

**Comment by ByeongHyunPak** [comment]
Thank you for your detailed reply! If you don't mind, can I ask when you plan to release the source code? I'm looking forward to reproduce the experiments.

**Comment by mfahes** [comment]
There is no clear plan currently, ideally i'll try  releasing it in January.
