### ISSUE TITLE
performance reach to 50.06% on GTAV -> Cityscapes?

### ISSUE THREAD

**Issue by tpy001** [astra-vision/FAMix#5]
Hi, thanks for you great work!

**Comment by tpy001** [comment]
I tested the checkpoint of ResNet101 + DeepLabv2 you provided and found it achieves 50.06% performance on Cityscapes, slightly higher than the 49.5% reported in the paper.
For Cityscapes, I noticed you test directly on  images with resolutions of 2048x1024.
However, scaling images to 1024x512 first, then upsampling predictions to 2048x1024, not only leads to faster inference but also yields better performance.

**Comment by tpy001** [comment]
I modified the validate function in main.py.    
![1](https://github.com/user-attachments/assets/3ae2b019-15c3-4d76-8bc3-3d11a429095c)

**Comment by mfahes** [comment]
Hi, thanks for your interest in the work.

The performances could be slightly higher or lower than the ones reported in the paper because the paper numbers are averages of 3 runs.

Scaling down the images and upsampling the predictions is interesting, thanks. I just tested it on other datasets with the same scale value (0.5), it improves also the results on Mapillary and ACDC in general (sometimes up to ~5-7 points mIoU compared to the paper, especially for ACDC night and fog). It seems to be beneficial to deploy the model with an input size close to the one used during training.
