### ISSUE TITLE
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 256, 4096]], which is output 0 of AsStridedBackward0, is at version 9; expected version 8 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

### ISSUE THREAD

**Issue by jxthyatt** [astra-vision/FAMix#7]
Thanks for your nice fix [https://github.com/astra-vision/FAMix/issues/6](url).

Before the fix, I run python3 patch_PIN.py --dataset synthia and get RuntimeError: "im2col_out_cpu" not implemented for 'Byte'. After the fix, I run python3 patch_PIN.py --dataset synthia and now it works.

However, when I run python3 main.py --dataset synthia, it fails to work.

Device: cuda
Dataset: synthia, Train set: 30, Val set: 944
[!] Retrain
Traceback (most recent call last):
  File "main.py", line 319, in <module>
    main()
  File "main.py", line 268, in main
    loss.backward()
  File "/mnt/home/jxt/miniconda3/envs/FAMix_env/lib/python3.8/site-packages/torch/_tensor.py", line 488, in backward
    torch.autograd.backward(
  File "/mnt/home/jxt/miniconda3/envs/FAMix_env/lib/python3.8/site-packages/torch/autograd/__init__.py", line 197, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation: [torch.cuda.FloatTensor [2, 256, 4096]], which is output 0 of AsStridedBackward0, is at version 9; expected version 8 instead. Hint: enable anomaly detection to find the operation that failed to compute its gradient, with torch.autograd.set_detect_anomaly(True).

Thanks again.

**Comment by mfahes** [comment]
Hi, this is because in the training I've put only gta5 and cityscapes options. It should work for synthia now [L133](https://github.com/astra-vision/FAMix/blob/907f66eb110e498b492bd1a523ef5078cbfe99a7/main.py#L133) [L224](https://github.com/astra-vision/FAMix/blob/907f66eb110e498b492bd1a523ef5078cbfe99a7/main.py#L224). In these lines i freeze the backbone except the last block of the last layer which is trained. Before adding synthia, the default setting is to train all the backbone, and the error comes from the fact that there's an inplace operation on the features of Layer1 (please see [this](https://github.com/astra-vision/FAMix/blob/main/network/utils.py)).

**Comment by jxthyatt** [comment]
I got it! Thanks a lot.
